---
title: "mediation analysis"
author: "Bastiaan"
date: "2023-09-20"
output:
  html_document:
    latex_engine: xelatex
    keep_tex: yes
  pdf_document: default
  word_document: default
---


```{r echo=FALSE }
# load packages
library(readr)
library(dplyr)
library(broom)
library(ggplot2)
library(car)
library(stargazer)
library(lubridate)
library(kableExtra)
library(corrplot)
library(openxlsx)






df <- read_csv("~/Master/Thesis/gen/data-preparation/output/thanos_endgame.csv", 
                           col_types = cols(imdb.com_releasedate = col_datetime(format = "%Y-%d-%m")))
```

```{r echo=FALSE}

df <- df %>%
  dplyr::select(-"imdb.com_releasedate")



#Left join thanos$imdb.com_releasedate to df 
df <- df %>%
  left_join(thanos %>% dplyr::select(imdb.com_imdbid, imdb.com_releasedate),
            by = c("imdb.com_imdbid" = "imdb.com_imdbid"))
  

df_clean <- df %>%
  filter(imdb.com_year >= 2000)
```

```{r echo=FALSE}
# Create new columns for each year from 2000 to 2019
for (year in 2000:2019) {
  col_name <- as.character(year)  # Convert the year to a character
  df_clean[col_name] <- ifelse(df_clean$imdb.com_year == year, 1, 0)
}

df_clean$Metascore <- as.numeric(df_clean$Metascore)

# Replace NA values with zero in specific columns
df_clean$Nominee <- ifelse(is.na(df_clean$Nominee), 0, df_clean$Nominee)
df_clean$Winner <- ifelse(is.na(df_clean$Winner), 0, df_clean$Winner)
df_clean$imdb.com_remake <- ifelse(is.na(df_clean$imdb.com_remake), 0, df_clean$imdb.com_remake)
df_clean$simpson_index <- ifelse(is.na(df_clean$simpson_index), 0, df_clean$simpson_index)
df_clean$boxofficemojo.com_openingtheaters <- ifelse(is.na(df_clean$boxofficemojo.com_openingtheaters), 0, df_clean$boxofficemojo.com_openingtheaters)
df_clean$the_numbers_com_dirpower_rank <- ifelse(is.na(df_clean$the_numbers_com_dirpower_rank), 0, df_clean$the_numbers_com_dirpower_rank)
df_clean$Metascore <- ifelse(is.na(df_clean$Metascore), 0, df_clean$Metascore)
df_clean$Total_Star_Power <- ifelse(is.na(df_clean$Total_Star_Power), 0 , df_clean$Total_Star_Power)

# Apply log transformation with small_constant
small_constant <- 0.1  # Define your small constant value

df_clean$log_Nominee <- log(df_clean$Nominee + small_constant)
df_clean$log_Winner <- log(df_clean$Winner + small_constant)
df_clean$log_remake <- log(df_clean$imdb.com_remake + small_constant)
df_clean$log_simpson_index <- log(df_clean$simpson_index + small_constant)
df_clean$log_op_theater <- log(df_clean$boxofficemojo.com_openingtheaters + small_constant)
df_clean$log_dir_power <- log(df_clean$the_numbers_com_dirpower_rank + small_constant)
df_clean$log_metascore <- log(df_clean$Metascore + small_constant)
df_clean$log_starpower <-log(df_clean$Total_Star_Power + small_constant)
df_clean$log_MPAA <- log(df_clean$mpaa_numeric + small_constant)
df_clean$log_sequel <- log(df_clean$imdb.com_sequel + small_constant)


# Seasonality
# Create a new column for each season
df_clean$Spring <- ifelse(month(df_clean$imdb.com_releasedate) %in% c(3, 4, 5), 1, 0)
df_clean$Summer <- ifelse(month(df_clean$imdb.com_releasedate) %in% c(6, 7, 8), 1, 0)
df_clean$Fall <- ifelse(month(df_clean$imdb.com_releasedate) %in% c(9, 10, 11), 1, 0)
df_clean$Winter <- ifelse(month(df_clean$imdb.com_releasedate) %in% c(12, 1, 2), 1, 0)


```

## For AIR we first need to filter which films were able to be parched 

```{r echo = FALSE }
df_clean_AIR <- df_clean[complete.cases(df_clean$Hispanic_condition_t2), ]

# Convert the dependent variables to factor variables
df_clean_AIR$Hispanic_condition_t3 <- factor(df_clean_AIR$Hispanic_condition_t3)
df_clean_AIR$Black_condition_t3 <- factor(df_clean_AIR$Black_condition_t3)
df_clean_AIR$Asian_condition_t3 <- factor(df_clean_AIR$Asian_condition_t3)

```

## Path A
```{r echo = FALSE}
# Fit a binary logistic regression model
model_path_hisp <- glm(
    Hispanic_condition_t3 ~
    simpson_index +
    log(boxofficemojo.com_openingtheaters) + 
                log(imdb.com_runtime) + log_MPAA + 
                log(average_budget) + 
                log_sequel + 
                imdb.com_spinoff +
                log_remake +
                imdb.com_basedonbook + 
                imdb.com_basedonplay + 
                imdb.com_basedoncomicbook + 
                imdb.com_basedonnovel + 
                imdb.com_basedonshortstory + 
                log_Nominee +
                log_Winner +
                log_dir_power +
                log_metascore + 
                log_starpower +
                 # Include all genre variables
                Action + Adventure + Comedy + Fantasy + Crime + Drama + Mystery + Thriller + Romance + Sci.Fi + Biography + Sport + War + Family + Musical + History + Horror + Music + Documentary + Western +
            # including seasonality
                Spring +
                Summer +
                Fall +
               # Adding the year dummy variables to the model (excluding 2000)
                `2001` + `2002` + `2003` + `2004` + `2005` + `2006` + `2007` + `2008` + `2009` + `2010` + `2011` + `2012` + `2013` + `2014` + `2015` + `2016` + `2017` + `2018` + `2019`,
  data = df_clean_AIR,
  family = binomial()  # Specify the family as binomial for binary logistic regression
)





# Fit a binary logistic regression model
model_path_asian <- glm(
    Asian_condition_t3 ~
    simpson_index +
    log(boxofficemojo.com_openingtheaters) + 
                log(imdb.com_runtime) + log_MPAA + 
                log(average_budget) + 
                log_sequel + 
                imdb.com_spinoff +
                log_remake +
                imdb.com_basedonbook + 
                imdb.com_basedonplay + 
                imdb.com_basedoncomicbook + 
                imdb.com_basedonnovel + 
                imdb.com_basedonshortstory + 
                log_Nominee +
                log_Winner +
                log_dir_power +
                log_metascore + 
                log_starpower +
                 # Include all genre variables
                Action + Adventure + Comedy + Fantasy + Crime + Drama + Mystery + Thriller + Romance + Sci.Fi + Biography + Sport + War + Family + Musical + History + Horror + Music + Documentary + Western +
            # including seasonality
                Spring +
                Summer +
                Fall +
               # Adding the year dummy variables to the model (excluding 2000)
                `2001`+`2002` + `2003` + `2004` + `2005` + `2006` + `2007` + `2008` + `2009` + `2010` + `2011` + `2012` + `2013` + `2014` + `2015` + `2016` + `2017` + `2018` + `2019`,
  data = df_clean_AIR,
  family = binomial()  # Specify the family as binomial for binary logistic regression
)



# Fit a binary logistic regression model
model_path_black <- glm(
    Black_condition_t3 ~
    simpson_index +
    log(boxofficemojo.com_openingtheaters) + 
                log(imdb.com_runtime) + log_MPAA + 
                log(average_budget) + 
                log_sequel + 
                imdb.com_spinoff +
                log_remake +
                imdb.com_basedonbook + 
                imdb.com_basedonplay + 
                imdb.com_basedoncomicbook + 
                imdb.com_basedonnovel + 
                imdb.com_basedonshortstory + 
                log_Nominee +
                log_Winner +
                log_dir_power +
                log_metascore + 
                log_starpower +
                 # Include all genre variables
                Action + Adventure + Comedy + Fantasy + Crime + Drama + Mystery + Thriller + Romance + Sci.Fi + Biography + Sport + War + Family + Musical + History + Horror + Music + Documentary + Western +
            # including seasonality
                Spring +
                Summer +
                Fall +
               # Adding the year dummy variables to the model (excluding 2000)
                `2001` + `2002` + `2003` + `2004` + `2005` + `2006` + `2007` + `2008` + `2009` + `2010` + `2011` + `2012` + `2013` + `2014` + `2015` + `2016` + `2017` + `2018` + `2019`,
  data = df_clean_AIR,
  family = binomial()  # Specify the family as binomial for binary logistic regression
)

summary(model_path_black)
summary(model_path_asian)
summary(model_path_hisp)


```


# Creating table result all three models
```{r echo=FALSE}

# Create a list of the three model objects
models_list <- list(
  model_path_hisp,
  model_path_asian,
  model_path_black
)

# Define custom names for the models
model_names <- c("Hispanic", "Asian", "Black")

# Use stargazer to generate a table
table <- stargazer(
  models_list,
  title = "Logistic Regression Models by Ethnicity",
  align = TRUE,  # Align coefficients
  column.labels = model_names,  # Specify model names
  dep.var.labels = c("Hispanic", "Asian", "Black"),  # Specify dependent variable labels
  type = "text"  # Output the table as plain text
)

# Print the table
cat(table)

# Capture the output of the stargazer function
stargazer_output <- capture.output({
  stargazer(
    models_list,
    title = "Logistic Regression Models by Ethnicity",
    align = TRUE,  # Align coefficients
    column.labels = model_names,  # Specify model names
    dep.var.labels = c("Hispanic", "Asian", "Black"),  # Specify dependent variable labels
    type = "text"  # Output the table as plain text
  )
})

# Combine all the outputs into a single string
stargazer_output <- paste(stargazer_output, collapse = "\n")

# Write the formatted table output into an Excel file
writeLines(stargazer_output, "Logistic_Regression_Models.txt")

# Read the text file
data <- readLines("Logistic_Regression_Models.txt")

# Write to CSV
writeLines(data, "output.csv")
```





# multicollinearity 
```{r echo=FALSE}

# Calculate VIF for the first model
vif_hisp <- vif(model_path_hisp)
vif_dataframe_hips <- data.frame(VIF_Values = vif_hisp)


# Calculate VIF for the second model
vif_asian <- vif(model_path_asian)
vif_dataframe_asian <- data.frame(VIF_Values = vif_asian)

# Calculate VIF for the third model
vif_black <- vif(model_path_black)
vif_dataframe_black <- data.frame(VIF_Values = vif_black)

vif_values <- cbind(vif_dataframe_black, vif_dataframe_asian, vif_dataframe_hips)

# Rename the columns
colnames(vif_values) <- c("Black", "Asian", "Hispanic")

# Print VIF values for each model
print("VIF for Hispanic model:")
print(vif_hisp)

print("VIF for Asian model:")
print(vif_asian)

print("VIF for Black model:")
print(vif_black)

```

# colleration matrix
```{r echo=FALSE}
model_columns <- c(
    "simpson_index", "Hispanic_condition_t3", "Black_condition_t3", "Asian_condition_t3",
    "screens", "log_imdb.com_runtime", "log_mpaa_numeric",
    "average_budget", "imdb.com_sequel", "imdb.com_spinoff", "log_remake",
    "imdb.com_basedonbook", "imdb.com_basedonplay",
    "imdb.com_basedoncomicbook", "imdb.com_basedonnovel", "imdb.com_basedonshortstory",
    "log_Nominee", "log_Winner", "log_dir_power", "log_metascore", "log_starpower",
    "Action", "Adventure", "Comedy", "Fantasy", "Crime", "Drama", "Mystery", "Thriller",
    "Romance", "Sci.Fi", "Biography", "Sport", "War", "Family", "Musical", "History",
    "Horror", "Music", "Documentary", "Western",
    "Spring", "Summer", "Fall", "Winter",
    "2000", "2001", "2002", "2003", "2004", "2005", "2006", "2007", "2008", "2009", "2010",
    "2011", "2012", "2013", "2014", "2015", "2016", "2017", "2018", "2019", "Avg_Rank_Third_Year"
)

# Selecting relevant columns
selected_columns <- c("imdb.com_metascore", "imdb.com_sequel", "Avg_Rank_First_Year", "rank_release", "Avg_Rank_Third_Year", "rank_two_weeks_before_release")


# Convert specific columns to numeric
df_clean_AIR$Hispanic_condition_t3 <- as.numeric(df_clean_AIR$Hispanic_condition_t3)
df_clean_AIR$Black_condition_t3 <- as.numeric(df_clean_AIR$Black_condition_t3)
df_clean_AIR$Asian_condition_t3 <- as.numeric(df_clean_AIR$Asian_condition_t3)
df_clean_AIR$Budget <- as.numeric(df_clean_AIR$average_budget)
df_clean_AIR$screens <- as.numeric(df_clean_AIR$boxofficemojo.com_openingtheaters)

# Subtract 1 from each value in the specified columns
df_clean_AIR$Hispanic_condition_t3 <- df_clean_AIR$Hispanic_condition_t3 - 1
df_clean_AIR$Black_condition_t3 <- df_clean_AIR$Black_condition_t3 - 1
df_clean_AIR$Asian_condition_t3 <- df_clean_AIR$Asian_condition_t3 - 1


# Filter out rows with missing values in the selected columns
df_clean_AIR_no_missing <- df_clean_AIR[complete.cases(df_clean_AIR[, selected_columns]), ]




# Select only the numeric variables from df_clean_AIR
numeric_data <- df_clean_AIR_no_missing[, sapply(df_clean_AIR_no_missing, is.numeric)]



# Filter numeric_data for columns used in the model
numeric_data <- numeric_data[, names(numeric_data) %in% model_columns]



# Compute the correlation matrix
correlation_matrix <- cor(numeric_data)


# Convert the correlation matrix to a data frame
correlation_df <- as.data.frame(correlation_matrix)

# Write the correlation matrix data frame to an Excel file
write.xlsx(correlation_df, "correlation_matrix.xlsx", asTable = TRUE)


# Define the threshold for high collinearity
threshold <- 0.5

# Find rows and columns with correlation coefficients greater than the defined threshold
high_collinearity <- which(abs(cor_matrix) > threshold & abs(cor_matrix) < 1, arr.ind = TRUE)

# Print the row and column names with high collinearity
for (i in 1:nrow(high_collinearity)) {
  row_idx <- high_collinearity[i, 1]
  col_idx <- high_collinearity[i, 2]
  row_name <- rownames(cor_matrix)[row_idx]
  col_name <- colnames(cor_matrix)[col_idx]
  correlation <- cor_matrix[row_idx, col_idx]
  cat("High collinearity between", row_name, "and", col_name, "with correlation:", correlation, "\n")
}

```


# model fit 

```{r echo=FALSE}
anova(model_path_asian,test="LRT")

```

## Path B
```{r echo = FALSE}
# Create the main regression model
model_path_b <- lm(log(Avg_Rank_Third_Year) ~
                Hispanic_condition_t3 +
                Black_condition_t3 +
                Asian_condition_t3 +
                log(boxofficemojo.com_openingtheaters) + 
                log(imdb.com_runtime) + log(mpaa_numeric) + 
                log(average_budget) + 
                imdb.com_sequel + 
                imdb.com_spinoff +
                log_remake +
                imdb.com_basedonbook + 
                imdb.com_basedonplay + 
                imdb.com_basedoncomicbook + 
                imdb.com_basedonnovel + 
                imdb.com_basedonshortstory + 
                log_Nominee +
                log_Winner +
                log_dir_power +
                log_metascore + 
                log_starpower +
                 # Include all genre variables
                Action + Adventure + Comedy + Fantasy + Crime + Drama + Mystery + Thriller + Romance + Sci.Fi + Biography + Sport + War + Family + Musical + History + Horror + Music + Documentary + Western +
            # including seasonality
                Spring +
                Summer +
                Fall +
               # Adding the year dummy variables to the model (excluding 2000)
                `2001` + `2002` + `2003` + `2004` + `2005` + `2006` + `2007` + `2008` + `2009` + `2010` + `2011` + `2012` + `2013` + `2014` + `2015` + `2016` + `2017` + `2018` + `2019`,
            data = df_clean_AIR)

model_coef <- summary(model_path_b)$coefficients

# Converting coefficients and standard errors to a dataframe
model_df <- data.frame(
  Coefficients = model_coef[, 1],
  Standard_Error = model_coef[, 2]
)



# Extracting coefficients, their standard errors, and significance stars
model_summary <- summary(model)
model_coef <- model_summary$coefficients

# Extracting significance stars
signif_stars <- ifelse(model_coef[,4] < 0.001, '***', ifelse(model_coef[,4] < 0.01, '**', ifelse(model_coef[,4] < 0.05, '*', '')))

# Combining coefficients, standard errors, and significance stars into a dataframe
model_df <- data.frame(
  Coefficients = model_coef[, 1],
  Standard_Error = model_coef[, 2],
  Significance = signif_stars
)

# Displaying the dataframe
print(model_df)
```


# Multi
```{r echo=FALSE}
# Calculate VIF for the first model
vif_b <- vif(model_path_b)

print(vif_b)
```

# Homoskedacity path B 
```{r echo=FALSE}

# Extract the residuals from the model
residuals <- residuals(model)

# Generate a set of quantiles from a normal distribution with the same mean and standard deviation as the residuals
expected_quantiles <- qnorm(ppoints(length(residuals)), mean = mean(residuals), sd = sd(residuals))

# Create the P-P plot
plot(expected_quantiles, sort(residuals), xlab = "Expected Quantiles", ylab = "Observed Quantiles")
abline(0, 1, col = "red")


# Perform the White test for heteroskedasticity
white_test <- bptest(model_path_b)

# Print the White test results
print(white_test)

# Calculate robust standard errors
robust_se <- sqrt(diag(vcovHC(model, type = "HC3")))

# View the summary of your model
summary(model)

# Apply robust standard errors to the model coefficients
coeftest(model, vcov = vcovHC, type = "HC1")

# Extract the robust standard errors
robust_se <- sqrt(diag(vcovHC(model, type = "HC3")))

# Extract the model coefficients
model_coefs <- coef(model)

# Extract the p-values
p_values <- summary(model)$coefficients[, "Pr(>|t|)"]

# Create a function to format p-values
format_p_value <- function(p) {
  if (p < 0.001) {
    return(paste("< 0.001", "***"))
  } else {
    return(paste(signif(p, digits = 4), " "))
  }
}

# Apply the format_p_value function to the p-values
formatted_p_values <- sapply(p_values, format_p_value)

# Combine the coefficients, their robust standard errors, and p-values
coefs_se_pvalues <- data.frame(Coefficient = model_coefs, `Robust SE` = robust_se, `P-value` = formatted_p_values)

# Create a table using kable
kable(coefs_se_pvalues, format = "markdown")
```


## Path c
```{r echo = FALSE}
# Create the main regression model
model_path_c <- lm(log(Avg_Rank_Third_Year) ~
                simpson_index +
                Hispanic_condition_t3 +
                Black_condition_t3 +
                Asian_condition_t3 +
                log(boxofficemojo.com_openingtheaters) + 
                log(imdb.com_runtime) + log(mpaa_numeric) + 
                log(average_budget) + 
                imdb.com_sequel + 
                imdb.com_spinoff +
                log_remake +
                imdb.com_basedonbook + 
                imdb.com_basedonplay + 
                imdb.com_basedoncomic + 
                imdb.com_basedoncomicbook + 
                imdb.com_basedonnovel + 
                imdb.com_basedonshortstory + 
                log_Nominee +
                log_Winner +
                log_dir_power +
                log_metascore + 
                log_starpower +
                 # Include all genre variables
                Action + Adventure + Comedy + Fantasy + Crime + Drama + Mystery + Thriller + Romance + Sci.Fi + Biography + Sport + War + Family + Musical + History + Horror + Music + Documentary + Western +
            # including seasonality
                Spring +
                Summer +
                Fall +
               # Adding the year dummy variables to the model (excluding 2000)
                `2001` + `2002` + `2003` + `2004` + `2005` + `2006` + `2007` + `2008` + `2009` + `2010` + `2011` + `2012` + `2013` + `2014` + `2015` + `2016` + `2017` + `2018` + `2019`,
            data = df_clean_AIR)


# print model 
summary(model_path_c)
```

```{r echo=FALSE}
# Calculate VIF for the first model
vif_c <- vif(model_path_c)

print(vif_c)
```