---
title: "logistic regression"
author: "Bastiaan"
date: "2023-12-08"
output: html_document
---


## Path A
```{r echo = FALSE, message= FALSE, warning=FALSE}
# Fit a binary logistic regression model
model_path_hisp <- glm(
    Hispanic_condition_t3 ~
    simpson_index +
    log(boxofficemojo.com_openingtheaters) + 
                log(imdb.com_runtime) + log_MPAA + 
                log(average_budget) + 
                log_sequel + 
                imdb.com_spinoff +
                log_remake +
                imdb.com_basedonbook + 
                imdb.com_basedonplay + 
                imdb.com_basedoncomicbook + 
                imdb.com_basedonnovel + 
                imdb.com_basedonshortstory + 
                log_Nominee +
                log_Winner +
                log_dir_power +
                log_metascore + 
                log_starpower +
                 # Include all genre variables
                Action + Adventure + Comedy + Fantasy + Crime + Drama + Mystery + Thriller + Romance + Sci.Fi + Biography + Sport + War + Family + Musical + History + Horror + Music + Documentary + Western +
            # including seasonality
                Spring +
                Summer +
                Fall +
               # Adding the year dummy variables to the model (excluding 2000)
                `2001` + `2002` + `2003` + `2004` + `2005` + `2006` + `2007` + `2008` + `2009` + `2010` + `2011` + `2012` + `2013` + `2014` + `2015` + `2016` + `2017` + `2018` + `2019`,
  data = df_clean_AIR,
  family = binomial()  # Specify the family as binomial for binary logistic regression
)





# Fit a binary logistic regression model
model_path_asian <- glm(
    Asian_condition_t3 ~
    simpson_index +
    log(boxofficemojo.com_openingtheaters) + 
                log(imdb.com_runtime) + log_MPAA + 
                log(average_budget) + 
                log_sequel + 
                imdb.com_spinoff +
                log_remake +
                imdb.com_basedonbook + 
                imdb.com_basedonplay + 
                imdb.com_basedoncomicbook + 
                imdb.com_basedonnovel + 
                imdb.com_basedonshortstory + 
                log_Nominee +
                log_Winner +
                log_dir_power +
                log_metascore + 
                log_starpower +
                 # Include all genre variables
                Action + Adventure + Comedy + Fantasy + Crime + Drama + Mystery + Thriller + Romance + Sci.Fi + Biography + Sport + War + Family + Musical + History + Horror + Music + Documentary + Western +
            # including seasonality
                Spring +
                Summer +
                Fall +
               # Adding the year dummy variables to the model (excluding 2000)
                `2001`+`2002` + `2003` + `2004` + `2005` + `2006` + `2007` + `2008` + `2009` + `2010` + `2011` + `2012` + `2013` + `2014` + `2015` + `2016` + `2017` + `2018` + `2019`,
  data = df_clean_AIR,
  family = binomial()  # Specify the family as binomial for binary logistic regression
)



# Fit a binary logistic regression model
model_path_black <- glm(
    Black_condition_t3 ~
    simpson_index +
    log(boxofficemojo.com_openingtheaters) + 
                log(imdb.com_runtime) + log_MPAA + 
                log(average_budget) + 
                log_sequel + 
                imdb.com_spinoff +
                log_remake +
                imdb.com_basedonbook + 
                imdb.com_basedonplay + 
                imdb.com_basedoncomicbook + 
                imdb.com_basedonnovel + 
                imdb.com_basedonshortstory + 
                log_Nominee +
                log_Winner +
                log_dir_power +
                log_metascore + 
                log_starpower +
                 # Include all genre variables
                Action + Adventure + Comedy + Fantasy + Crime + Drama + Mystery + Thriller + Romance + Sci.Fi + Biography + Sport + War + Family + Musical + History + Horror + Music + Documentary + Western +
            # including seasonality
                Spring +
                Summer +
                Fall +
               # Adding the year dummy variables to the model (excluding 2000)
                `2001` + `2002` + `2003` + `2004` + `2005` + `2006` + `2007` + `2008` + `2009` + `2010` + `2011` + `2012` + `2013` + `2014` + `2015` + `2016` + `2017` + `2018` + `2019`,
  data = df_clean_AIR,
  family = binomial()  # Specify the family as binomial for binary logistic regression
)
```


# Creating table result all three models
```{r echo=FALSE, message= FALSE, warning=FALSE}

# Create a list of the three model objects
models_list <- list(
  model_path_hisp,
  model_path_asian,
  model_path_black
)

# Define custom names for the models
model_names <- c("Hispanic", "Asian", "Black")

# Use stargazer to generate a table
table <- stargazer(
  models_list,
  title = "Logistic Regression Models by Ethnicity",
  align = TRUE,  # Align coefficients
  column.labels = model_names,  # Specify model names
  dep.var.labels = c("Hispanic", "Asian", "Black"),  # Specify dependent variable labels
  type = "text"  # Output the table as plain text
)

# Capture the output of the stargazer function
stargazer_output <- capture.output({
  stargazer(
    models_list,
    title = "Logistic Regression Models by Ethnicity",
    align = TRUE,  # Align coefficients
    column.labels = model_names,  # Specify model names
    dep.var.labels = c("Hispanic", "Asian", "Black"),  # Specify dependent variable labels
    type = "text"  # Output the table as plain text
  )
})

# Combine all the outputs into a single string
stargazer_output <- paste(stargazer_output, collapse = "\n")

# Write the formatted table output into an Excel file
writeLines(stargazer_output, "Logistic_Regression_Models.txt")
```





# multicollinearity 
```{r echo=FALSE, message= FALSE, warning=FALSE}

# Calculate VIF for the first model
vif_hisp <- vif(model_path_hisp)
vif_dataframe_hips <- data.frame(VIF_Values = vif_hisp)


# Calculate VIF for the second model
vif_asian <- vif(model_path_asian)
vif_dataframe_asian <- data.frame(VIF_Values = vif_asian)

# Calculate VIF for the third model
vif_black <- vif(model_path_black)
vif_dataframe_black <- data.frame(VIF_Values = vif_black)

vif_values <- cbind(vif_dataframe_black, vif_dataframe_asian, vif_dataframe_hips)

# Rename the columns
colnames(vif_values) <- c("Black", "Asian", "Hispanic")

# Print VIF values for each model
print("VIF for Hispanic model:")
print(vif_hisp)

print("VIF for Asian model:")
print(vif_asian)

print("VIF for Black model:")
print(vif_black)

```



# model fit 

```{r echo=FALSE, message= FALSE, warning=FALSE}
anova(model_path_asian,test="LRT")

```



## Path A T2
```{r echo = FALSE, message= FALSE, warning=FALSE}
# Fit a binary logistic regression model
model_path_hisp_t2 <- glm(
    Hispanic_condition_t2 ~
    simpson_index +
    log(boxofficemojo.com_openingtheaters) + 
                log(imdb.com_runtime) + log_MPAA + 
                log(average_budget) + 
                log_sequel + 
                imdb.com_spinoff +
                log_remake +
                imdb.com_basedonbook + 
                imdb.com_basedonplay + 
                imdb.com_basedoncomicbook + 
                imdb.com_basedonnovel + 
                imdb.com_basedonshortstory + 
                log_Nominee +
                log_Winner +
                log_dir_power +
                log_metascore + 
                log_starpower +
                 # Include all genre variables
                Action + Adventure + Comedy + Fantasy + Crime + Drama + Mystery + Thriller + Romance + Sci.Fi + Biography + Sport + War + Family + Musical + History + Horror + Music + Documentary + Western +
            # including seasonality
                Spring +
                Summer +
                Fall +
               # Adding the year dummy variables to the model (excluding 2000)
                `2001` + `2002` + `2003` + `2004` + `2005` + `2006` + `2007` + `2008` + `2009` + `2010` + `2011` + `2012` + `2013` + `2014` + `2015` + `2016` + `2017` + `2018` + `2019`,
  data = df_clean_AIR,
  family = binomial()  # Specify the family as binomial for binary logistic regression
)





# Fit a binary logistic regression model
model_path_asian_t2 <- glm(
    Asian_condition_t2 ~
    simpson_index +
    log(boxofficemojo.com_openingtheaters) + 
                log(imdb.com_runtime) + log_MPAA + 
                log(average_budget) + 
                log_sequel + 
                imdb.com_spinoff +
                log_remake +
                imdb.com_basedonbook + 
                imdb.com_basedonplay + 
                imdb.com_basedoncomicbook + 
                imdb.com_basedonnovel + 
                imdb.com_basedonshortstory + 
                log_Nominee +
                log_Winner +
                log_dir_power +
                log_metascore + 
                log_starpower +
                 # Include all genre variables
                Action + Adventure + Comedy + Fantasy + Crime + Drama + Mystery + Thriller + Romance + Sci.Fi + Biography + Sport + War + Family + Musical + History + Horror + Music + Documentary + Western +
            # including seasonality
                Spring +
                Summer +
                Fall +
               # Adding the year dummy variables to the model (excluding 2000)
                `2001`+`2002` + `2003` + `2004` + `2005` + `2006` + `2007` + `2008` + `2009` + `2010` + `2011` + `2012` + `2013` + `2014` + `2015` + `2016` + `2017` + `2018` + `2019`,
  data = df_clean_AIR,
  family = binomial()  # Specify the family as binomial for binary logistic regression
)



# Fit a binary logistic regression model
model_path_black_t2 <- glm(
    Black_condition_t2 ~
    simpson_index +
    log(boxofficemojo.com_openingtheaters) + 
                log(imdb.com_runtime) + log_MPAA + 
                log(average_budget) + 
                log_sequel + 
                imdb.com_spinoff +
                log_remake +
                imdb.com_basedonbook + 
                imdb.com_basedonplay + 
                imdb.com_basedoncomicbook + 
                imdb.com_basedonnovel + 
                imdb.com_basedonshortstory + 
                log_Nominee +
                log_Winner +
                log_dir_power +
                log_metascore + 
                log_starpower +
                 # Include all genre variables
                Action + Adventure + Comedy + Fantasy + Crime + Drama + Mystery + Thriller + Romance + Sci.Fi + Biography + Sport + War + Family + Musical + History + Horror + Music + Documentary + Western +
            # including seasonality
                Spring +
                Summer +
                Fall +
               # Adding the year dummy variables to the model (excluding 2000)
                `2001` + `2002` + `2003` + `2004` + `2005` + `2006` + `2007` + `2008` + `2009` + `2010` + `2011` + `2012` + `2013` + `2014` + `2015` + `2016` + `2017` + `2018` + `2019`,
  data = df_clean_AIR,
  family = binomial()  # Specify the family as binomial for binary logistic regression
)
```

```{r echo=FALSE, message= FALSE, warning=FALSE}

# Create a list of the three model objects
models_list <- list(
  model_path_black_t2,
  model_path_asian_t2,
  model_path_hisp_t2
)

# Define custom names for the models
model_names <- c("Hispanic", "Asian", "Black")

# Use stargazer to generate a table
table <- stargazer(
  models_list,
  title = "Logistic Regression Models by Ethnicity",
  align = TRUE,  # Align coefficients
  column.labels = model_names,  # Specify model names
  dep.var.labels = c("Hispanic", "Asian", "Black"),  # Specify dependent variable labels
  type = "text"  # Output the table as plain text
)

# Capture the output of the stargazer function
stargazer_output <- capture.output({
  stargazer(
    models_list,
    title = "Logistic Regression Models by Ethnicity",
    align = TRUE,  # Align coefficients
    column.labels = model_names,  # Specify model names
    dep.var.labels = c("Hispanic", "Asian", "Black"),  # Specify dependent variable labels
    type = "text"  # Output the table as plain text
  )
})

# Combine all the outputs into a single string
stargazer_output <- paste(stargazer_output, collapse = "\n")

# Write the formatted table output into an Excel file
writeLines(stargazer_output, "Logistic_Regression_Models.txt")
```

