---
title: "mediation analysis"
author: "Bastiaan"
date: "2023-09-20"
output:
  html_document:
    code_folding: hide
    keep_md: true
    message: false
---


```{r echo=FALSE, message= FALSE, warning=FALSE}
# load packages
library(readr)
library(dplyr)
library(broom)
library(ggplot2)
library(car)
library(stargazer)
library(lubridate)
library(kableExtra)
library(corrplot)
library(openxlsx)
library(tidyr)
library(lmtest)






df <- read_csv("../../gen/data-preparation/output/thanos_endgame_air.csv", 
                           col_types = cols(imdb.com_releasedate = col_datetime(format = "%Y-%d-%m")))

thanos <- read_csv("../../gen/data-preparation/output/thanos.csv", 
                           col_types = cols(imdb.com_releasedate = col_datetime(format = "%Y-%d-%m")))
```

# Filtering the dataset
```{r echo=FALSE , message= FALSE , warning=FALSE }

df <- df %>%
  dplyr::select(-"imdb.com_releasedate")



#Left join thanos$imdb.com_releasedate to df 
df <- df %>%
  left_join(thanos %>% dplyr::select(imdb.com_imdbid, imdb.com_releasedate),
            by = c("imdb.com_imdbid" = "imdb.com_imdbid"))
  

df_clean <- df %>%
  filter(imdb.com_year >= 2000)



```

# Transformation variables
```{r echo=FALSE, message= FALSE, warning=FALSE}
# Create new columns for each year from 2000 to 2019
for (year in 2000:2019) {
  col_name <- as.character(year)  # Convert the year to a character
  df_clean[col_name] <- ifelse(df_clean$imdb.com_year == year, 1, 0)
}

df_clean$Metascore <- as.numeric(df_clean$Metascore)

# Replace NA values with zero in specific columns
df_clean$Nominee <- ifelse(is.na(df_clean$Nominee), 0, df_clean$Nominee)
df_clean$Winner <- ifelse(is.na(df_clean$Winner), 0, df_clean$Winner)
df_clean$the_numbers_com_dirpower_rank <- ifelse(is.na(df_clean$the_numbers_com_dirpower_rank), 0, df_clean$the_numbers_com_dirpower_rank)

# Apply log transformation with small_constant
small_constant <- 1  # Define your small constant value

df_clean$log_Nominee <- log(df_clean$Nominee  + small_constant)
df_clean$log_Winner <- log(df_clean$Winner + small_constant)
df_clean$log_remake <- log(df_clean$imdb.com_remake * 100 + small_constant)
df_clean$log_dir_power <- log(df_clean$the_numbers_com_dirpower_rank * 100  + small_constant)
df_clean$log_metascore <- log(df_clean$Metascore + small_constant)
df_clean$log_starpower <-log(df_clean$Total_Star_Power * 100 + small_constant)
df_clean$log_MPAA <- log(df_clean$mpaa_numeric + small_constant)
df_clean$imdb.com_sequel <- ifelse(df_clean$imdb.com_sequel == 0, 0, 1)


# Seasonality
# Create a new column for each season
df_clean$Spring <- ifelse(month(df_clean$imdb.com_releasedate) %in% c(3, 4, 5), 1, 0)
df_clean$Summer <- ifelse(month(df_clean$imdb.com_releasedate) %in% c(6, 7, 8), 1, 0)
df_clean$Fall <- ifelse(month(df_clean$imdb.com_releasedate) %in% c(9, 10, 11), 1, 0)
df_clean$Winter <- ifelse(month(df_clean$imdb.com_releasedate) %in% c(12, 1, 2), 1, 0)


```

## For AIR we first need to filter which films were able to be parched 

```{r echo = FALSE , message= FALSE, warning=FALSE}
df_clean_AIR <- df_clean[complete.cases(df_clean$Hispanic_condition_t2), ]

# Convert the dependent variables to factor variables
df_clean_AIR$Hispanic_condition_t3 <- factor(df_clean_AIR$Hispanic_condition_t3)
df_clean_AIR$Black_condition_t3 <- factor(df_clean_AIR$Black_condition_t3)
df_clean_AIR$Asian_condition_t3 <- factor(df_clean_AIR$Asian_condition_t3)

```





# colleration matrix
```{r echo=FALSE, message= FALSE, warning=FALSE}
model_columns <- c(
    "simpson_index", "Hispanic_condition_t3", "Black_condition_t3", "Asian_condition_t3",
    "screens", "log_imdb.com_runtime", "log_mpaa_numeric",
    "average_budget", "imdb.com_sequel", "imdb.com_spinoff", "log_remake",
    "imdb.com_basedonbook", "imdb.com_basedonplay",
    "imdb.com_basedoncomicbook", "imdb.com_basedonnovel", "imdb.com_basedonshortstory",
    "log_Nominee", "log_Winner", "log_dir_power", "log_metascore", "log_starpower",
    "Action", "Adventure", "Comedy", "Fantasy", "Crime", "Drama", "Mystery", "Thriller",
    "Romance", "Sci.Fi", "Biography", "Sport", "War", "Family", "Musical", "History",
    "Horror", "Music", "Documentary", "Western",
    "Spring", "Summer", "Fall", "Winter",
    "2000", "2001", "2002", "2003", "2004", "2005", "2006", "2007", "2008", "2009", "2010",
    "2011", "2012", "2013", "2014", "2015", "2016", "2017", "2018", "2019", "Avg_Rank_Third_Year", "rank_release", "boxofficemojo.com_openinggross"
)




# Convert specific columns to numeric
df_clean_AIR$Hispanic_condition_t3 <- as.numeric(df_clean_AIR$Hispanic_condition_t3)
df_clean_AIR$Black_condition_t3 <- as.numeric(df_clean_AIR$Black_condition_t3)
df_clean_AIR$Asian_condition_t3 <- as.numeric(df_clean_AIR$Asian_condition_t3)
df_clean_AIR$Budget <- as.numeric(df_clean_AIR$average_budget)
df_clean_AIR$screens <- as.numeric(df_clean_AIR$boxofficemojo.com_openingtheaters)
# Remove non-numeric characters and convert to numeric
df_clean_AIR$boxofficemojo.com_openinggross <- as.numeric(gsub("[^0-9.]", "", df_clean_AIR$boxofficemojo.com_openinggross))

# Subtract 1 from each value in the specified columns
df_clean_AIR$Hispanic_condition_t3 <- df_clean_AIR$Hispanic_condition_t3 - 1
df_clean_AIR$Black_condition_t3 <- df_clean_AIR$Black_condition_t3 - 1
df_clean_AIR$Asian_condition_t3 <- df_clean_AIR$Asian_condition_t3 - 1

# Selecting relevant columns
selected_columns <- c("imdb.com_metascore", "imdb.com_sequel", "Avg_Rank_First_Year", "rank_release", "Avg_Rank_Third_Year", "rank_two_weeks_before_release")

# Filter out rows with missing values in the selected columns
df_clean_AIR_no_missing <- df_clean_AIR[complete.cases(df_clean_AIR[, selected_columns]), ]


# Select only the numeric variables from df_clean_AIR
numeric_data <- df_clean_AIR_no_missing[, sapply(df_clean_AIR_no_missing, is.numeric)]


# Filter numeric_data for columns used in the model
numeric_data <- numeric_data[, names(numeric_data) %in% model_columns]


# Compute the correlation matrix
correlation_matrix <- cor(numeric_data)


# Convert the correlation matrix to a data frame
correlation_df <- as.data.frame(correlation_matrix)

# Write the correlation matrix data frame to an Excel file
write.xlsx(correlation_df, "correlation_matrix.xlsx", asTable = TRUE)


# Define the threshold for high collinearity
threshold <- 0.5

```

# path B t1
## Path B
```{r echo = FALSE, message= FALSE, warning=FALSE}
# Create the main regression model
model_path_b_t1 <- lm(log(Avg_Rank_Third_Year) ~
                hispanic_t1 +
                black_t1 +
                asian_t1 +
                log(boxofficemojo.com_openingtheaters) + 
                log(imdb.com_runtime) + log(mpaa_numeric) + 
                log(average_budget) + 
                imdb.com_sequel + 
                imdb.com_spinoff +
                log_remake +
                imdb.com_basedonbook + 
                imdb.com_basedonplay + 
                imdb.com_basedoncomicbook + 
                imdb.com_basedonnovel + 
                imdb.com_basedonshortstory + 
                log_Nominee +
                log_Winner +
                log_dir_power +
                log_metascore + 
                log_starpower +
                 # Include all genre variables
                Action + Adventure + Comedy + Fantasy + Crime + Drama + Mystery + Thriller + Romance + Sci.Fi + Biography + Sport + War + Family + Musical + History + Horror + Music + Documentary + Western +
            # including seasonality
                Spring +
                Summer +
                Fall +
               # Adding the year dummy variables to the model (excluding 2000)
                `2001` + `2002` + `2003` + `2004` + `2005` + `2006` + `2007` + `2008` + `2009` + `2010` + `2011` + `2012` + `2013` + `2014` + `2015` + `2016` + `2017` + `2018` + `2019`,
            data = df_clean_AIR)

summary(model_path_b_t1)
```






# Multi
```{r echo=FALSE, message= FALSE, warning=FALSE}
# Calculate VIF for the first model
vif_b <- vif(model_path_b)

print(vif_b)
```




# path B t2
## Path B
```{r echo = FALSE, message= FALSE, warning=FALSE}
# Create the main regression model
model_path_b_t2 <- lm(log(Avg_Rank_Third_Year) ~
                Hispanic_condition_t2 +
                Black_condition_t2 +
                Asian_condition_t2 +
                log(boxofficemojo.com_openingtheaters) + 
                log(imdb.com_runtime) + log(mpaa_numeric) + 
                log(average_budget) + 
                imdb.com_sequel + 
                imdb.com_spinoff +
                log_remake +
                imdb.com_basedonbook + 
                imdb.com_basedonplay + 
                imdb.com_basedoncomicbook + 
                imdb.com_basedonnovel + 
                imdb.com_basedonshortstory + 
                log_Nominee +
                log_Winner +
                log_dir_power +
                log_metascore + 
                log_starpower +
                 # Include all genre variables
                Action + Adventure + Comedy + Fantasy + Crime + Drama + Mystery + Thriller + Romance + Sci.Fi + Biography + Sport + War + Family + Musical + History + Horror + Music + Documentary + Western +
            # including seasonality
                Spring +
                Summer +
                Fall +
               # Adding the year dummy variables to the model (excluding 2000)
                `2001` + `2002` + `2003` + `2004` + `2005` + `2006` + `2007` + `2008` + `2009` + `2010` + `2011` + `2012` + `2013` + `2014` + `2015` + `2016` + `2017` + `2018` + `2019`,
            data = df_clean_AIR)

summary(model_path_b_t2)
```



## Path B
```{r echo = FALSE, message= FALSE, warning=FALSE}
# Create the main regression model
model_path_b <- lm(log(Avg_Rank_Third_Year) ~
                Hispanic_condition_t3 +
                Black_condition_t3 +
                Asian_condition_t3 +
                log(boxofficemojo.com_openingtheaters) + 
                log(imdb.com_runtime) + log(mpaa_numeric) + 
                log(average_budget) + 
                imdb.com_sequel + 
                imdb.com_spinoff +
                log_remake +
                imdb.com_basedonbook + 
                imdb.com_basedonplay + 
                imdb.com_basedoncomicbook + 
                imdb.com_basedonnovel + 
                imdb.com_basedonshortstory + 
                log_Nominee +
                log_Winner +
                log_dir_power +
                log_metascore + 
                log_starpower +
                 # Include all genre variables
                Action + Adventure + Comedy + Fantasy + Crime + Drama + Mystery + Thriller + Romance + Sci.Fi + Biography + Sport + War + Family + Musical + History + Horror + Music + Documentary + Western +
            # including seasonality
                Spring +
                Summer +
                Fall +
               # Adding the year dummy variables to the model (excluding 2000)
                `2001` + `2002` + `2003` + `2004` + `2005` + `2006` + `2007` + `2008` + `2009` + `2010` + `2011` + `2012` + `2013` + `2014` + `2015` + `2016` + `2017` + `2018` + `2019`,
            data = df_clean_AIR)

summary(model_path_b)

model_coef <- summary(model_path_b)$coefficients

# Converting coefficients and standard errors to a dataframe
model_df <- data.frame(
  Coefficients = model_coef[, 1],
  Standard_Error = model_coef[, 2]
)



# Extracting coefficients, their standard errors, and significance stars
model_summary <- summary(model_path_b )
model_coef <- model_summary$coefficients

# Extracting significance stars
signif_stars <- ifelse(model_coef[,4] < 0.001, '***', ifelse(model_coef[,4] < 0.01, '**', ifelse(model_coef[,4] < 0.05, '*', '')))

# Combining coefficients, standard errors, and significance stars into a dataframe
model_df <- data.frame(
  Coefficients = model_coef[, 1],
  Standard_Error = model_coef[, 2],
  Significance = signif_stars
)

# Displaying the dataframe
print(model_df)
```




# comparison path B T1, T2 , T3 
```{r echo = FALSE, message= FALSE, warning=FALSE}
# Get model summaries
model_summaries <- bind_rows(
  glance(model_path_b) %>% mutate(model = "model_path_b"),
  glance(model_path_b_t2) %>% mutate(model = "model_path_b_t2"),
  glance(model_path_b_t1) %>% mutate(model = "model_path_b_t1")
)

# Writing the model summaries to an Excel file
write.xlsx(model_summaries, "model_summaries.xlsx")


# Get model coefficients with significance
model_coefficients <- bind_rows(
  tidy(model_path_b) %>% mutate(model = "model_path_b"),
  tidy(model_path_b_t2) %>% mutate(model = "model_path_b_t2"),
  tidy(model_path_b_t1) %>% mutate(model = "model_path_b_t1"),
)

model_coefficients_with_stars <- model_coefficients %>%
  mutate(
    significance = case_when(
      p.value < 0.001 ~ '***',
      p.value < 0.01 ~ '**',
      p.value < 0.05 ~ '*',
      TRUE ~ ''  # If none of the above conditions are met
    ),
    estimate = round(estimate, 3)  # Rounding 'estimate' to 3 decimal places
  )


model_coefficients_with_stars <- model_coefficients_with_stars %>%
  mutate(
    combined_estimate = paste(estimate, significance, sep = " ") # Creating a new variable by concatenating 'estimate' and 'significance'
  )

model_coefficients_pivot <- model_coefficients_with_stars %>%
  select(-std.error, -statistic, -p.value, -estimate, -significance) %>%  # Remove unnecessary columns
  spread(key = model, value = combined_estimate)

# Writing the model summaries to an Excel file
write.xlsx(model_coefficients_pivot, "model_coefficients.xlsx")


# Create a list of the three model objects
models_b <- list(
  model_path_b,
  model_path_b_t2,
  model_path_b_t1
)

# Define custom names for the models
model_names <- c("T3", "T2", "T1", "T1 AIR")

# Use stargazer to generate a table
table <- stargazer(
  models_b,
  title = "Models path B",
  align = TRUE,  # Align coefficients
  column.labels = model_names,  # Specify model names
  dep.var.labels = c("Hispanic", "Asian", "Black"),  # Specify dependent variable labels
  type = "text"  # Output the table as plain text
)


# Capture the output of the stargazer function
stargazer_output <- capture.output({
  stargazer(
    models_list,
    title = "Logistic Regression Models by Ethnicity",
    align = TRUE,  # Align coefficients
    column.labels = model_names,  # Specify model names
    dep.var.labels = c("Hispanic", "Asian", "Black"),  # Specify dependent variable labels
    type = "text"  # Output the table as plain text
  )
})

# Combine all the outputs into a single string
stargazer_output <- paste(stargazer_output, collapse = "\n")

# Write the formatted table output into an Excel file
writeLines(stargazer_output, "Logistic_Regression_Models.txt")

```

###### extra ########

## Path B
```{r echo = FALSE, message= FALSE, warning=FALSE}
# Create the main regression model
model_path_b_default <- lm(log(Avg_Rank_Third_Year) ~
                log(boxofficemojo.com_openingtheaters) + 
                log(imdb.com_runtime) + log(mpaa_numeric) + 
                log(average_budget) + 
                imdb.com_sequel + 
                imdb.com_spinoff +
                log_remake +
                imdb.com_basedonbook + 
                imdb.com_basedonplay + 
                imdb.com_basedoncomicbook + 
                imdb.com_basedonnovel + 
                imdb.com_basedonshortstory + 
                log_Nominee +
                log_Winner +
                log_dir_power +
                log_metascore + 
                log_starpower +
                 # Include all genre variables
                Action + Adventure + Comedy + Fantasy + Crime + Drama + Mystery + Thriller + Romance + Sci.Fi + Biography + Sport + War + Family + Musical + History + Horror + Music + Documentary + Western +
            # including seasonality
                Spring +
                Summer +
                Fall +
               # Adding the year dummy variables to the model (excluding 2000)
                `2001` + `2002` + `2003` + `2004` + `2005` + `2006` + `2007` + `2008` + `2009` + `2010` + `2011` + `2012` + `2013` + `2014` + `2015` + `2016` + `2017` + `2018` + `2019`,
            data = df_clean_AIR)

summary(model_path_b_default)
```
## compariso main regression with sample of AIR 
```{r echo = FALSE, message= FALSE, warning=FALSE}
# Create the main regression model
model_comp_sample <- lm(log(Avg_Rank_Third_Year) ~
                simpson_index +
                log(boxofficemojo.com_openingtheaters) + 
                log(imdb.com_runtime) + log(mpaa_numeric) + 
                log(average_budget) + 
                imdb.com_sequel + 
                imdb.com_spinoff +
                log_remake +
                imdb.com_basedonbook + 
                imdb.com_basedonplay + 
                imdb.com_basedoncomicbook + 
                imdb.com_basedonnovel + 
                imdb.com_basedonshortstory + 
                log_Nominee +
                log_Winner +
                log_dir_power +
                log_metascore + 
                log_starpower +
                 # Include all genre variables
                Action + Adventure + Comedy + Fantasy + Crime + Drama + Mystery + Thriller + Romance + Sci.Fi + Biography + Sport + War + Family + Musical + History + Horror + Music + Documentary + Western +
            # including seasonality
                Spring +
                Summer +
                Fall +
               # Adding the year dummy variables to the model (excluding 2000)
                `2001` + `2002` + `2003` + `2004` + `2005` + `2006` + `2007` + `2008` + `2009` + `2010` + `2011` + `2012` + `2013` + `2014` + `2015` + `2016` + `2017` + `2018` + `2019`,
            data = df_clean_AIR)

summary(model_comp_sample)
```

## Path c
```{r echo = FALSE, message= FALSE, warning=FALSE}
# Create the main regression model
model_path_c <- lm(log(Avg_Rank_Third_Year) ~
                Hispanic_condition_t3 * simpson_index +
                Black_condition_t3 * simpson_index +
                Asian_condition_t3 * simpson_index +
                log(boxofficemojo.com_openingtheaters) + 
                log(imdb.com_runtime) + log(mpaa_numeric) + 
                log(average_budget) + 
                imdb.com_sequel + 
                imdb.com_spinoff +
                log_remake +
                imdb.com_basedonbook + 
                imdb.com_basedonplay + 
                imdb.com_basedoncomic + 
                imdb.com_basedoncomicbook + 
                imdb.com_basedonnovel + 
                imdb.com_basedonshortstory + 
                log_Nominee +
                log_Winner +
                log_dir_power +
                log_metascore + 
                log_starpower +
                 # Include all genre variables
                Action + Adventure + Comedy + Fantasy + Crime + Drama + Mystery + Thriller + Romance + Sci.Fi + Biography + Sport + War + Family + Musical + History + Horror + Music + Documentary + Western +
            # including seasonality
                Spring +
                Summer +
                Fall +
               # Adding the year dummy variables to the model (excluding 2000)
                `2001` + `2002` + `2003` + `2004` + `2005` + `2006` + `2007` + `2008` + `2009` + `2010` + `2011` + `2012` + `2013` + `2014` + `2015` + `2016` + `2017` + `2018` + `2019`,
            data = df_clean_AIR)


# print model 
summary(model_path_c)
```

```{r echo=FALSE, message= FALSE, warning=FALSE}
# Calculate VIF for the first model
vif_c <- vif(model_path_c)

print(vif_c)
```